language: c
compiler: gcc
script:
  - make cvode
  - make pihm
  - make clean && make pihm-fbr
  - make clean && make flux-pihm
  - make clean && make flux-pihm-fbr
  - make clean && make flux-pihm-bgc
  - make clean && make rt-flux-pihm
  - make clean && make OMP=off pihm
  - make clean && make OMP=off pihm-fbr
  - make clean && make OMP=off flux-pihm
  - make clean && make OMP=off flux-pihm-fbr
  - make clean && make OMP=off flux-pihm-bgc
  - make clean && make OMP=off rt-flux-pihm
branches:
  only:
  - master
